name: Publish docs

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: desionlab/vue-vcl
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm i && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
